Repository DIT113-V22/group-07, pull requests merged in 2022-05, with the labels that each got.

#72 Update .gitignore
  .gitignore
Labels: 🐛 Bug

#77 Update intro screen
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/IntroFragment.kt
  GreenGarbageApp/app/src/main/res/drawable/box.xml
  GreenGarbageApp/app/src/main/res/drawable/garbagetruck_s_2.png
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
Labels: 🥈 Sprint #2, 🎨 Design

#76 Update game screen layout
  GreenGarbageApp/app/src/main/res/drawable/garbagetruck_s.png
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
Labels: 🥈 Sprint #2, 🎨 Design

#75 Throttle control
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  arduino/smartcar/smartcar.ino
Labels: 🥈 Sprint #2

#80 50 speedometer
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/MainActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  arduino/smartcar/smartcar.ino
Labels: 🥈 Sprint #2

#85 Add splash screen
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/Splash_screen.kt
  GreenGarbageApp/app/src/main/res/layout/activity_splash_screen.xml
  GreenGarbageApp/app/src/main/res/values/themes.xml
Labels: ✨ Enhancement, 🎨 Design, 🥉 Sprint #3

#87 Camera feed colors
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
Labels: 🥈 Sprint #2

#88 Added vehicle_config.json & board_config.json to git repository
  arduino/smartcar/board_config.json
  arduino/smartcar/vehicle_config.json
Labels: ✨ Enhancement, 🥈 Sprint #2

#90 update UN info view
  GreenGarbageApp/app/src/main/res/layout/fragment_u_ninfo.xml
  GreenGarbageApp/app/src/main/res/values/colors.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: ✨ Enhancement, 🎨 Design, 🥉 Sprint #3

#91 About us
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/AboutFragment.kt
  GreenGarbageApp/app/src/main/res/drawable/github_icon.png
  GreenGarbageApp/app/src/main/res/drawable/github_mark_32px.png
  GreenGarbageApp/app/src/main/res/drawable/github_mark_64px.png
  GreenGarbageApp/app/src/main/res/drawable/shadow_button.xml
  GreenGarbageApp/app/src/main/res/drawable/trash.png
  GreenGarbageApp/app/src/main/res/layout/fragment_about.xml
  GreenGarbageApp/app/src/main/res/menu/nav_drawer.xml
  GreenGarbageApp/app/src/main/res/navigation/navigation.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: ✨ Enhancement, 🎨 Design, 🥉 Sprint #3

#93 update LinearLayout on all layouts
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/IntroFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/NewGameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/StartFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/UNinfoFragment.kt
  GreenGarbageApp/app/src/main/res/drawable/box.xml
  GreenGarbageApp/app/src/main/res/drawable/camera_view.xml
  GreenGarbageApp/app/src/main/res/drawable/e_sdg_logo_un_emblem_horizontal_web.jpg
  GreenGarbageApp/app/src/main/res/drawable/gg_3.png
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_compost_24.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_phone_24.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_leaf.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_star.xml
  GreenGarbageApp/app/src/main/res/drawable/planet_earth.png
  GreenGarbageApp/app/src/main/res/layout-land/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout-land/fragment_start.xml
  GreenGarbageApp/app/src/main/res/layout/activity_main.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_about.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_end.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_legal.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_new_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_start.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_u_ninfo.xml
  GreenGarbageApp/app/src/main/res/menu/nav_drawer.xml
  GreenGarbageApp/app/src/main/res/values/colors.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
  GreenGarbageApp/app/src/main/res/values/themes.xml
Labels: ✨ Enhancement, 🎨 Design, 🥉 Sprint #3, 🧹 Clean up

#96 Sqlite database
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/MainActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/StartFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/Player.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDatabase.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerRepository.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerViewModel.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/AboutFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/ContactFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/EndFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/IntroFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/LegalFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/StartFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/UNinfoFragment.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_start.xml
  GreenGarbageApp/app/src/main/res/navigation/navigation.xml
  GreenGarbageApp/build.gradle
Labels: 🥉 Sprint #3, 🧹 Clean up

#83 speed displayed in km/h
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/res/drawable/speedometer.png
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
  arduino/smartcar/smartcar.ino
Labels: 🥈 Sprint #2

#98 Add background music
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/MainActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/res/drawable/ic_music_off.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_music_on.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_speed.xml
  GreenGarbageApp/app/src/main/res/drawable/pause.png
  GreenGarbageApp/app/src/main/res/drawable/quaver.png
  GreenGarbageApp/app/src/main/res/drawable/toggle_selector.xml
  GreenGarbageApp/app/src/main/res/layout/activity_main.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_about.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_contact.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_u_ninfo.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
  GreenGarbageApp/app/src/main/res/values/themes.xml
Labels: 🔈 Sound, 🥉 Sprint #3

#100 Leaderboard screen
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/LeaderboardAdapter.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/Player.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerRepository.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerViewModel.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/IntroFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/LeaderboardFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/StartFragment.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_leaderboard.xml
  GreenGarbageApp/app/src/main/res/layout/leaderboard_row.xml
  GreenGarbageApp/app/src/main/res/navigation/navigation.xml
Labels: 🥉 Sprint #3

#99 Updates variable names to be more readable
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
Labels: 🥉 Sprint #3, 🧹 Clean up

#103 #12 Add layout design on leaderboard
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/res/drawable/first_place.jpg
  GreenGarbageApp/app/src/main/res/drawable/second_place.jpg
  GreenGarbageApp/app/src/main/res/drawable/third_place.jpg
  GreenGarbageApp/app/src/main/res/layout/fragment_leaderboard.xml
Labels: ✨ Enhancement, 🎨 Design, 🥉 Sprint #3

#108 Save game
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/Player.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDatabase.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/EndFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/IntroFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/StartFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_end.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_start.xml
  GreenGarbageApp/app/src/main/res/navigation/navigation.xml
Labels: 🥉 Sprint #3

#111 #29 Add educational context on InfoScreen
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/CanFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/FoodWasteFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GlassFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/IntroFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/PaperFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/PlasticFragment.kt
  GreenGarbageApp/app/src/main/res/drawable/apple.png
  GreenGarbageApp/app/src/main/res/drawable/border_apple.xml
  GreenGarbageApp/app/src/main/res/drawable/border_can.xml
  GreenGarbageApp/app/src/main/res/drawable/border_glass.xml
  GreenGarbageApp/app/src/main/res/drawable/border_paper.xml
  GreenGarbageApp/app/src/main/res/drawable/border_plastic.xml
  GreenGarbageApp/app/src/main/res/drawable/bottle.png
  GreenGarbageApp/app/src/main/res/drawable/can.png
  GreenGarbageApp/app/src/main/res/drawable/ic_double_arrow_left.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_double_arrow_right.xml
  GreenGarbageApp/app/src/main/res/drawable/paper.png
  GreenGarbageApp/app/src/main/res/drawable/plastic.png
  GreenGarbageApp/app/src/main/res/layout/fragment_can.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_food_waste.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_glass.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_paper.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_plastic.xml
  GreenGarbageApp/app/src/main/res/values/colors.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: ✨ Enhancement, 🎨 Design, 🥉 Sprint #3

#110 Joystick implementation
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/libs/joystickjhr.aar
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/res/drawable/circle.png
  GreenGarbageApp/app/src/main/res/drawable/greenearth.png
  GreenGarbageApp/app/src/main/res/drawable/trashcan.png
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/settings.gradle
  arduino/smartcar/smartcar.ino
Labels: 🥉 Sprint #3

#115 Bugfix and add points to leaderboard
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDatabase.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/EndFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
Labels: 🐛 Bug, 🥉 Sprint #3

#116 #107 Database testing
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/LiveDataUtilAndroidTest.kt
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/database/DatabaseTest.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/Player.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDatabase.kt
Labels: 🥉 Sprint #3

#121 Update README.md
  README.md
Labels: 🧹 Clean up

#125 Instrumental tests for navigation
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/database/LiveDataUtilAndroidTest.kt
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/navigation/NavigationTest.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_can.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_food_waste.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_glass.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_paper.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_plastic.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_start.xml
Labels: 🏆 Sprint #4

#126 Clean up
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/LegalFragment.kt
  GreenGarbageApp/app/src/main/res/drawable/borde_circle_blue.png
  GreenGarbageApp/app/src/main/res/drawable/border_round.xml
  GreenGarbageApp/app/src/main/res/drawable/button_background.xml
  GreenGarbageApp/app/src/main/res/drawable/circle.png
  GreenGarbageApp/app/src/main/res/drawable/circle.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_end.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_legal.xml
  GreenGarbageApp/app/src/main/res/menu/nav_drawer.xml
  GreenGarbageApp/app/src/main/res/navigation/navigation.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
  GreenGarbageApp/build.gradle
  GreenGarbageApp/gradle/wrapper/gradle-wrapper.properties
Labels: 🏆 Sprint #4, 🧹 Clean up

#127 Revert "Instrumental tests for navigation"
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/LiveDataUtilAndroidTest.kt
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/navigation/NavigationTest.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_can.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_food_waste.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_glass.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_paper.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_plastic.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_start.xml
Labels: 🏆 Sprint #4

#120 Blinker reverse mode
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/res/anim/blink.xml
  GreenGarbageApp/app/src/main/res/drawable-anydpi/ic_blinker.xml
  GreenGarbageApp/app/src/main/res/drawable-hdpi/ic_blinker.png
  GreenGarbageApp/app/src/main/res/drawable-mdpi/ic_blinker.png
  GreenGarbageApp/app/src/main/res/drawable-xhdpi/ic_blinker.png
  GreenGarbageApp/app/src/main/res/drawable-xxhdpi/ic_blinker.png
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: 🏆 Sprint #4

#131 Keypad
  .DS_Store
  Custom Green Garbage/src/environments/example/Example.tscn
  Custom Green Garbage/src/objects/Bottle1.gd
  Custom Green Garbage/src/objects/BottleTest.tscn
  Custom Green Garbage/src/objects/Collision.tscn
  Custom Green Garbage/src/objects/Collision2.tscn
  Custom Green Garbage/src/objects/Collision3.tscn
  Custom Green Garbage/src/objects/Collision4.tscn
  Custom Green Garbage/src/objects/treepath 3.tscn
  Custom Green Garbage/src/textures/DB2X2_L01 2.png
  Custom Green Garbage/src/vehicles/SketchCar/GarbageTruck.tscn
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  arduino/smartcar/smartcar.ino
  arduino/smartcar/vehicle_config.json
Labels: ✨ Enhancement, 🏆 Sprint #4

#134 Input changes and design to leaderboard fragment
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_leaderboard.xml
  GreenGarbageApp/app/src/main/res/menu/nav_drawer.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🏆 Sprint #4, 🧹 Clean up

#136 Review screen changes
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerDao.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerRepository.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/database/PlayerViewModel.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/fragments/ReviewFragment.kt
Labels: ✨ Enhancement, 🏆 Sprint #4

#133 Navigation tests and CI change
  .github/workflows/android-ci.yml
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/database/LiveDataUtilAndroidTest.kt
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/navigation/NavigationTest.kt
  GreenGarbageApp/app/src/main/res/layout/fragment_can.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_food_waste.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_glass.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_paper.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_plastic.xml
Labels: 🏆 Sprint #4

#138 #137 - Removal of objects causing lagging
  Custom Green Garbage/src/environments/example/Example.tscn
  Custom Green Garbage/src/objects/Bottle1.gd
  Custom Green Garbage/src/objects/BottleTest.tscn
  Custom Green Garbage/src/objects/Can.tscn
  Custom Green Garbage/src/objects/Collision.tscn
  Custom Green Garbage/src/objects/Collision2.tscn
  Custom Green Garbage/src/objects/Collision3.tscn
  Custom Green Garbage/src/objects/Collision4.tscn
  Custom Green Garbage/src/objects/Wine.tscn
Labels: 🐛 Bug, 🧹 Clean up

#135 Update README.md
  README.md
Labels: 📝 Documentation

#139 Add picture
  README.md
Labels: 📝 Documentation

#140 Add YT demo video
  README.md
Labels: 📝 Documentation

#141 Fix typos
  README.md
Labels: 📝 Documentation
