Repository DIT113-V22/group-07, pull requests merged in 2022-04, with the labels that each got.

#34 Added android studio project in which we will build the application
  GreenGarbageApp/.gitignore
  GreenGarbageApp/app/.gitignore
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/proguard-rules.pro
  GreenGarbageApp/app/src/androidTest/java/com/example/greengarbageapp/ExampleInstrumentedTest.kt
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/MainActivity.kt
  GreenGarbageApp/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_launcher_background.xml
  GreenGarbageApp/app/src/main/res/layout/activity_main.xml
  GreenGarbageApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  GreenGarbageApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/values-night/themes.xml
  GreenGarbageApp/app/src/main/res/values/colors.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
  GreenGarbageApp/app/src/main/res/values/themes.xml
  GreenGarbageApp/app/src/test/java/com/example/greengarbageapp/ExampleUnitTest.kt
  GreenGarbageApp/build.gradle
  GreenGarbageApp/gradle.properties
  GreenGarbageApp/gradle/wrapper/gradle-wrapper.jar
  GreenGarbageApp/gradle/wrapper/gradle-wrapper.properties
  GreenGarbageApp/gradlew
  GreenGarbageApp/gradlew.bat
  GreenGarbageApp/settings.gradle
Labels: Sprint1

#33 Basic obstacle avoidance
  arduino/smartcar/smartcar.ino
Labels: Sprint1

#36 Added some continuous integration for the app and also changed permis…
  .github/workflows/android-ci.yml
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/gradlew
Labels: Sprint1

#37 Added code for controlling the car through the application (using MQT…
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/MainActivity.java
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/MainActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/MqttClient.java
  GreenGarbageApp/app/src/main/res/layout/activity_main.xml
  GreenGarbageApp/gradle.properties
  GreenGarbageApp/settings.gradle
Labels: Sprint1

#40 Refactoring from Java to Kotlin + added packages
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/MainActivity.java
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/MqttClient.java
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/GameActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttClient.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/res/layout/activity_main.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: Sprint1

#39 added install mqtt library also in arduino workflow
  .github/workflows/arduino-build.yml
Labels: Sprint1

#53 Add new Start Screen
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/Screen_1.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/screen_3.kt
  GreenGarbageApp/app/src/main/res/drawable/garbage_truck.png
  GreenGarbageApp/app/src/main/res/drawable/half_circle_darkgreen.xml
  GreenGarbageApp/app/src/main/res/drawable/half_circle_lightgreen.xml
  GreenGarbageApp/app/src/main/res/drawable/header.png
  GreenGarbageApp/app/src/main/res/font/almendra_bold.xml
  GreenGarbageApp/app/src/main/res/font/holtwood_one_sc.xml
  GreenGarbageApp/app/src/main/res/layout/activity_screen1.xml
  GreenGarbageApp/app/src/main/res/layout/activity_screen3.xml
  GreenGarbageApp/app/src/main/res/values/colors.xml
  GreenGarbageApp/app/src/main/res/values/font_certs.xml
  GreenGarbageApp/app/src/main/res/values/preloaded_fonts.xml
Labels: design

#54 Add new Intro Screen
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/intro_screen.kt
  GreenGarbageApp/app/src/main/res/drawable/box.xml
  GreenGarbageApp/app/src/main/res/drawable/garbagetruck_2.png
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_cancel_24.xml
  GreenGarbageApp/app/src/main/res/font/acme.xml
  GreenGarbageApp/app/src/main/res/layout/activity_intro_screen.xml
  GreenGarbageApp/app/src/main/res/values/preloaded_fonts.xml
  GreenGarbageApp/build.gradle
Labels: design

#56 Add new Game Screen
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/game_screen.kt
  GreenGarbageApp/app/src/main/res/drawable/camera_view.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_arrow_circle_left_24.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_arrow_circle_right_24.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_speed_24.xml
  GreenGarbageApp/app/src/main/res/drawable/ic_baseline_stop_circle_24.xml
  GreenGarbageApp/app/src/main/res/layout/activity_game_screen.xml
Labels: 🎨 Design

#62 Update on car modification
  Custom Green Garbage/src/vehicles/gb/VehicleBody.gd
Labels: 🥈 Sprint #2

#66 #51 Navigation through the app
  GreenGarbageApp/app/build.gradle
  GreenGarbageApp/app/src/main/AndroidManifest.xml
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/Screen_1.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/EndFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/GameActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/GameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/IntroFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/MainActivity.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/NewGameFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/activities/StartFragment.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/end_of_game_Screen.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/game_screen.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/intro_screen.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/mqtt/MqttSmartcar.kt
  GreenGarbageApp/app/src/main/java/com/example/greengarbageapp/screen_3.kt
  GreenGarbageApp/app/src/main/res/layout/activity_main.xml
  GreenGarbageApp/app/src/main/res/layout/activity_screen3.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_end.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_intro.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_new_game.xml
  GreenGarbageApp/app/src/main/res/layout/fragment_start.xml
  GreenGarbageApp/app/src/main/res/navigation/navigation.xml
  GreenGarbageApp/app/src/main/res/values/strings.xml
Labels: 🥈 Sprint #2

#69 Add GG app icon and updated app theme
  GreenGarbageApp/app/src/main/ic_launcher-playstore.png
  GreenGarbageApp/app/src/main/res/drawable/ic_launcher_background.xml
  GreenGarbageApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  GreenGarbageApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher.png
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  GreenGarbageApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher.png
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  GreenGarbageApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  GreenGarbageApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  GreenGarbageApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  GreenGarbageApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  GreenGarbageApp/app/src/main/res/values/ic_launcher_background.xml
  GreenGarbageApp/app/src/main/res/values/themes.xml
Labels: 🥈 Sprint #2, 🎨 Design
